DRY

diff --git a/ifttt b/ifttt
--- a/ifttt
+++ b/ifttt
@@ -2,23 +2,20 @@
 
 set -e
 
-if [ "$1" == '' ]; then
-	echo 'Missing event' 1>&2
+die() {
+	echo "$@" 1>&2
 	exit 1
-fi
+}
+
+[ "$1" == '' ] && die 'Missing event'
 
 conf=$HOME/.ifttt.json
 
-if [ ! -f $conf ]; then
-	echo "Missing configuration file: $conf" 1>&2
-	exit 1
-fi
+[ ! -f $conf ] && die "Missing configuration file: $conf"
 
 mode=$(stat -c '%a' $conf)
-if [ $mode -ne 600 -a $mode -ne 400 ]; then
-	echo "$conf must have 600 or 400 permissions" 2>&1
-	exit 1
-fi
+[ $mode -ne 600 -a $mode -ne 400 ] && \
+	die "$conf must have 600 or 400 permissions"
 
 apiKey=$(<$conf jq -r .api_key)
 
