Rationalize quoting

diff --git a/ifttt b/ifttt
--- a/ifttt
+++ b/ifttt
@@ -2,8 +2,8 @@
 
 set -e
 
-if [ "$1" == "" ]; then
-	echo "Missing event" 1>&2
+if [ "$1" == '' ]; then
+	echo 'Missing event' 1>&2
 	exit 1
 fi
 
@@ -14,20 +14,20 @@ if [ ! -f $conf ]; then
 	exit 1
 fi
 
-mode=$(stat -c "%a" $conf)
+mode=$(stat -c '%a' $conf)
 if [ $mode -ne 600 -a $mode -ne 400 ]; then
 	echo "$conf must have 600 or 400 permissions" 2>&1
 	exit 1
 fi
 
-apiKey=$(<$conf jq -r '.api_key')
+apiKey=$(<$conf jq -r .api_key)
 
 event=$1
 payload='{}'
 index=1
 
 shift
-until [ "$1" == "" -o $index -gt 3 ]; do
+until [ "$1" == '' -o $index -gt 3 ]; do
 	payload=$(
 		echo $payload | jq -c --arg value "$1" ". + { value$index: \$value }"
 	)
@@ -38,6 +38,6 @@ done
 
 echo $payload | curl \
 	-sS --output /dev/null \
-	-H "Content-Type: application/json" \
+	-H 'Content-Type: application/json' \
 	--data @- \
 	https://maker.ifttt.com/trigger/$event/with/key/$apiKey
